DROP DATABASE IF EXISTS INVESTMENTS;
CREATE DATABASE IF NOT EXISTS INVESTMENTS
  DEFAULT CHARACTER SET utf8
  COLLATE utf8_general_ci;
USE INVESTMENTS;

CREATE TABLE IF NOT EXISTS PROJECTS (
  ID            INT PRIMARY KEY AUTO_INCREMENT AUTO_INCREMENT,
  NAME          VARCHAR(100) NOT NULL,
  SOLUTION      VARCHAR(500) NOT NULL,
  FINAL_COST    INT          NOT NULL,
  ASSEMBLE_COST INT          NOT NULL,
  OWNER         VARCHAR(50)  NOT NULL
)
  ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS USERS (
  ID      INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  NAME    VARCHAR(50)                    NOT NULL,
  SURNAME VARCHAR(50)                    NOT NULL,
  ADRESS  VARCHAR(100)                   NOT NULL,
  PHONE   INT                            NOT NULL,
  ROLE    VARCHAR(25)                    NOT NULL
)
  ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS PROJECT_OWNERS (
  ID         INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  ID_PROJECT INT                            NOT NULL,
  ID_USER    INT                            NOT NULL,

  FOREIGN KEY (ID_PROJECT) REFERENCES PROJECTS (ID),
  FOREIGN KEY (ID_USER) REFERENCES USERS (ID)
)
  ENGINE InnoDB;

CREATE TABLE IF NOT EXISTS INVESTMENTS (
  ID         INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  SUM        INT                            NOT NULL,
  USER_ID    INT                            NOT NULL,
  PROJECT_ID INT                            NOT NULL,

  FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS (ID)
)
  ENGINE InnoDB;