INSERT INTO investments (SUM) VALUES (2000);
INSERT INTO investments (SUM) VALUES (1000);
INSERT INTO investments (SUM) VALUES (1000);
INSERT INTO investments (SUM) VALUES (3500);
INSERT INTO investments (SUM) VALUES (2500);
INSERT INTO investments (SUM) VALUES (2500);