INSERT INTO USERS (NAME, SURNAME, ADRESS, PHONE, ROLE)
VALUES ("ALEKSEY", "GIRYA", "KIEV KULIBINA 6 STREET", 0993694390, "ADMIN");
INSERT INTO USERS (NAME, SURNAME, ADRESS, PHONE, ROLE)
VALUES ("ANDREY", "DEMCHUK", "KIEV TROECHINA", 0993694390, "ADMIN");