INSERT INTO investments (SUM, USER_ID, PROJECT_ID) VALUES (2000, 1, 1);
INSERT INTO investments (SUM, USER_ID, PROJECT_ID) VALUES (1000, 1, 2);
INSERT INTO investments (SUM, USER_ID, PROJECT_ID) VALUES (1000, 2, 2);
INSERT INTO investments (SUM, USER_ID, PROJECT_ID) VALUES (3500, 1, 3);
INSERT INTO investments (SUM, USER_ID, PROJECT_ID) VALUES (2500, 1, 4);
INSERT INTO investments (SUM, USER_ID, PROJECT_ID) VALUES (2500, 2, 4);